{
"test": {
	"scope": "lua",
	"prefix": ["test","uwu"],
	"body":[

	],
	"description": "This Snippet was auto generated by @Prooheckcp's program"
	},
"second": {
	"scope": "lua",
	"prefix": ["second"],
	"body":[
		"local second = \"haha\""
	],
	"description": "This Snippet was auto generated by @Prooheckcp's program"
	}
}